#!/bin/bash

#set -x

THIS_SCRIPT=$0
NAME=hvac-demo

ME_ABS=$(readlink -f $0)
MY_DIR=$(dirname $ME_ABS)

check_distro() {
	$MY_DIR/prj_script.sh check_distro $1 || exit 2
}

# setup user / sudo and other basic distro setup
distro_setup() {
	apt-get -qq update
	apt-get install -qqy sudo
	if id $MY_UID >/dev/null 2>&1; then
		OLD_USER=$(id -nu $MY_UID)
		echo "Removing user $OLD_USER, as it conflicts with user $MY_USER $MY_UID:$MY_GID"
		userdel $OLD_USER
	fi
	groupadd --gid $MY_GID $MY_USER
	useradd  --uid $MY_UID --gid $MY_GID --shell /bin/bash -mN $MY_USER
	groupadd --system sudo_np
	usermod -a -G sudo_np $MY_USER
	mkdir -p /etc/sudoers.d/
	echo "%sudo_np ALL=(ALL:ALL) NOPASSWD:ALL" >/etc/sudoers.d/sudo_np
	echo "$MY_USER ALL=(ALL:ALL) NOPASSWD:ALL" >/etc/sudoers.d/${MY_USER}_np
}

# This is suppose to be better than "su"
userjmp() {
    setpriv --reuid=$MY_UID --regid=$MY_GID --init-groups --reset-env "$@"
}

do_once() {
	NAME=$1; shift
	if [ ! -e ~/.done/$NAME.done ]; then
		"$@"
		mkdir -p ~/.done
		echo "done" >~/.done/$NAME.done
	fi
}

# main function when container is built dynamically and using a mounted volume
# This works for docker
container_main() {
	if [ "$EUID" -ne 0 ]; then
		echo "Error: container-main must be run as root"
		exit 2
	fi
	if [ ! -d /prj ]; then
		echo "Error: project directory not mounted at /prj"
		exit 2
	fi

	check_distro run

	cd /prj
	MY_UID=$(stat --format="%u" /prj)
	MY_GID=$(stat --format="%g" /prj)
	MY_USER="me"

	do_once distro_setup distro_setup
	userjmp /bin/bash -l
}

# first pass main for podman w/ mounted dir
# setup user and do distro_setup
podman_main1() {
	MY_USER=${1:-user}
	MY_UID=${2:-1000}
	MY_GID=${3:-1000}

	do_once distro_setup distro_setup
}

# on 2nd pass we will be running with the volume attached
# and with --userns=keep-id
podman_main2() {
	cd /prj
	/bin/bash -l
}

# function to build the container from a Dockerfile
container_build() {
	MY_UID=1000
	MY_GID=1000
	MY_USER=user

	if [ -e /.container-build-vars ]; then
		. /.container-build-vars
	fi

	do_once distro_setup distro_setup
	do_once admin_setup $MY_DIR/prj_script.sh admin_setup
	userjmp $THIS_SCRIPT do_once prj_setup $MY_DIR/prj_script.sh prj_setup
	userjmp $THIS_SCRIPT do_once container_build_user container_build_user
}

# the part of container_build to be run as the user
container_build_user() {
	URL=https://github.com/wmamills/hvac-demo.git
	BRANCH=main
	VER=""

	if [ -e /.container-build-vars ]; then
		. /.container-build-vars
	fi

	cd
	git clone $URL hvac-demo
	cd ~/hvac-demo
	if [ -n "$BRANCH" ]; then
		git checkout $BRANCH
	fi
	if [ -n "$VER" ]; then
		git fetch origin $VER
		git reset --hard $VER
	fi

	# prefetch images
	./scripts/maybe-fetch host/$(uname -m)
	./scripts/maybe-fetch target
	./scripts/maybe-fetch zephyr.tar.gz
	./scripts/maybe-fetch disk/debian-12-arm64-big.qcow2.bz2
	./scripts/maybe-fetch disk/virtio_msg_rootfs.cpio.gz

	# now delete the results, just save the git-lfs fetch
	rm -rf build images
}

case $1 in
do_once|container_build|podman_main1|podman_main2)
	"$@"
	;;
*)
	container_main "$@"
	;;
esac
