FROM debian:12

# wildcard on vars file makes it conditional
COPY container-main prj_script.sh .container-build-vars* /
RUN /container-main container_build
RUN rm /container-main /prj_script.sh

USER user
WORKDIR /home/user/hvac-demo
